name: Main

on: push

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os:   [ubuntu-latest, macos-latest, windows-latest]
        os:   [ubuntu-latest]
        node: [12, 14]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v1"
        with: { node-version: "${{ matrix.node }}" }
      - run: npm ci
      - run: npm run test
